spring:
  application:
    name: confsvr
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:\Users\cemmr\Code\Active\spmia\ch-3\confsvr\src\main\resources\config

server:
  port: 8888